version: "3.9"

services:
  golangService:
    build:
      context: .
      dockerfile: Dockerfile
    image: socialbackend:latest
    container_name: socialbackend
    volumes:
      - ../:/usr/app/
    ports:
      - "7700:7700"
    restart: always
    stdin_open: true
    depends_on:
      - database
    links:
      - database
    logging:
      driver: none
  database:
    image: mongo
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_DATABASE=Mgo
    volumes:
      - ./mongo-volume:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    logging:
      driver: none
